# Generated by Django 5.1.1 on 2024-10-19 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_clickanalytics_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clickanalytics',
            name='country',
        ),
        migrations.AlterField(
            model_name='clickanalytics',
            name='device',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clickanalytics',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.longtoshort'),
        ),
    ]
