# Generated by Django 5.1.1 on 2024-10-20 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_clickanalytics_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickanalytics',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='clickanalytics',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
