# Generated by Django 5.1.1 on 2024-10-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_clickanalytics_country_clickanalytics_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickanalytics',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
